### ISSUE TITLE
Allow MQTT wildcards in mqtt:publish operation

### ISSUE THREAD

**Issue by rodmaz** [aws-greengrass/aws-greengrass-client-device-auth#388]
**Feature Description**
Ability to support MQTT wildcards in in `mqtt:publish` operation.

**Use Case**
We are following [AWS MQTT best practices document](https://docs.aws.amazon.com/whitepapers/latest/designing-mqtt-topics-aws-iot-core/mqtt-design-best-practices.html), which proposes levels in MQTT topic. However we cannot include every single attribute level of MQTT in the `mqtt:publish` as it is dynamic by nature.
Also we are afraid of hitting a size limit of the component configuration document if we have to include every topic variant possible.
P.S. AWS does not inform about any size limit for the component configuration JSON.

**Proposed Solution**
Allow support for MQTT wildcards in `mqtt:publish` operation.

**Comment by rodmaz** [comment]
Hi @MikeDombo 

We tried to use something like this:

```
"AllowDeviceIoTPublishing": {
  "operations": [
    "mqtt:publish"
  ],
  "resources": [
    "mqtt:topic:dt/swx/swx-anchor-f412fa526bdc/+/location/update"
  ],
  "statementDescription": "Allow devices to publish IoT-related data."
}
```

We simply cannot foresee what would show up in that topic level, so we tried to use `+`.

Regarding the size limit for the component configuration, the Service Quotas mention _Maximum size of component recipe_ but not the size for the component configuration. These are separate things, right?
If we have to include all possible combinations in the `mqtt:publish`, the component configuration can become quite extensive and we are afraid of hitting a limit sometime in the future.

**Comment by rodmaz** [comment]
Meanwhile we are removing the dynamic parts of the topic and include them in the MQTT body. This goes a bit against the AWS MQTT best practices but it works.

**Comment by MikeDombo** [comment]
OK, thank you for that.

The link I sent was explicitly to the relevant "6MB - The deployment document includes the component configurations, deployment configurations, and payload overhead."

We are considering adding similar functionality in terms of policy variables.

**Comment by rodmaz** [comment]
Here is another situation which displays the urgent need to allow wildcards. 
We want to allow our Greengrass devices to publish in classic and named shadows. Right now for EACH Greengrass client we need to add this list of topics:

```[json]
          "AllowShadowTopicsPublishing": {
            "operations": [
              "mqtt:publish"
            ],
            "resources": [
              "mqtt:topic:$aws/things/swx-f412fa526bdc/shadow/get",
              "mqtt:topic:$aws/things/swx-f412fa526bdc/shadow/update",
              "mqtt:topic:$aws/things/swx-f412fa526bdc/shadow/name/connectivity/get",
              "mqtt:topic:$aws/things/swx-f412fa526bdc/shadow/name/radio/get",
              "mqtt:topic:$aws/things/swx-f412fa526bdc/shadow/name/bridge/get"
            ],
            "statementDescription": "Allow devices to publish to shadow topics."
          },
```

In case we have 10, 20 client devices in our Greengrass group, this quickly becomes huge.

**Comment by rodmaz** [comment]
Just updated the last comment with how the configuration looks like for the component when using 2(!) Greengrass connected things.
The scalability of our solution using the client device auth component is worrying us.

**Comment by MikeDombo** [comment]
Hello, as I said previously, this is something we're looking to add. Until that time, you would need to do what you posted or else use `*` to allow operations on all topics. That's not a security best practice, but in reality it is likely acceptable due to the layers of security including the MQTT bridge configuration and iot policy applied to the Greengrass core device.

**Comment by rodmaz** [comment]
@MikeDombo Sure, appreciate the attention to this. 

Let's just keep in mind that, according to documentation of the component, wildcards are only accepted in `mqtt:subscribe`. `mqtt:publish` does not accept wildcards.
And even in the case of `mqtt:subscribe`, the wildcards are part of the topic, not really _wildcards_.

> The client device can subscribe to the exact topic filters that you allow. For example, if you allow the client device to subscribe to the mqtt:topicfilter:client/+/status resource, the client device can subscribe to client/+/status but not client/client1/status.

**Comment by MikeDombo** [comment]
Yes that's correct. I am suggesting to subscribe using the MQTT wildcard `#`. For publish, you'd need to use `*` such that the device can publish to _any_ topic.

**Comment by MikeDombo** [comment]
This is now complete with release 2.5.0
