### ISSUE TITLE
Support monitoring connection status of local client devices

### ISSUE THREAD

**Issue by hatakeyama-nst** [aws-greengrass/aws-greengrass-client-device-auth#55]
**Feature Description**
Add support for monitoring connection status of local client devices.

**Use Case**
We would like to monitor connection state of all Greengrass Core and client devices from the Fleet Hub and Fleet Indexing connectivity.

**Proposed Solution**
It might be better to have Greengrass Core devices send out client device lifecycle events.

**Other**
The original issue : 
https://repost.aws/questions/QUn6YI_qx5SL28Vo2r42TFyg#ANgcOp1ZaHRj-Qh6J-VrZ67w

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by jbutler** [comment]
Hi there,

Thanks for opening this FR. It's certain a feature we've thought of, but haven't had a chance to work on a design yet.

Can you elaborate a little more on your use case? What information are you looking for and what would you do with it (e.g. trigger an alarm if a device isn't seen for X amount of time, push firmware updates, etc). Do you need to know the specific Greengrass device the client device is connected to?

Thanks,
-joe

**Comment by hatakeyama-nst** [comment]
Hi,
We want to trigger an alarm if a device isn't seen for a specified time, or by the state of device shadows.
Shadow Manager client device support (https://github.com/aws-greengrass/aws-greengrass-shadow-manager/issues/101) is also needed, though.
We are not necessary to know which Greengrass device the client device is connected to. We are trying to communicate only with a specific Greengrass Core.

It would be nice if there is a way other than parsing greengrass.log when the Greengrass Core component wants to detect client device connect/disconnect events.

**Comment by hatakeyama-nst** [comment]
Thank you for your suggestion.
It's great to hear that Client device shadow support is being worked on.

For now, we are planning to make client devices connecting with both IoT Core and Greengrass Core, which also allows to check the connection status.
